export const actions={
    doctor:{
        "DATA_FETCHING":"DOCTOR_DATA_FETCHING",
        "DATA_FETCHED":"DOCTOR_DATA_FETCHED",
        "DATA_FETCHED_ERROR":"DOCTOR_DATA_FETCH_ERROR",
        "DATA_CREATED":"DOCTOR_DATA_CREATED",
        "DATA_EDITED":"DOCTOR_DATA_EDITED",
        "DATA_DELETED":"DOCTOR_DATA_DELETED",
        "DOCTOR_IMAGE_UPDATED":"DOCTOR_IMAGE_UPDATED"
        
    }
}